### ISSUE TITLE
Bad window dimension in capture_window()

### ISSUE THREAD

**Issue by ghost** [h04x/win-screenshot#1]
I'm using win-screenshot to take screenshots of a specific window but there was a little problem with the resulting image. The dimension given to the image does not take into account the window frame and title bar. The resulting image is cropped because of this.

To fix the problem in my project I modified lines 72-73 of `lib.rs`:
``` rust
let width = (*rc).right - (*rc).left + 16;
let height = (*rc).bottom - (*rc).top + 39;
```

It works perfect for my resolution (1920x1080) and windows version (Win10 21H2) but of course it is not an universal fix.

**Comment by h04x** [comment]
Thank you for opened issue. Fixed by replacement GetClientRec() -> GetWindowRect()
