### ISSUE TITLE
Add option to pass rect parameters to capture_window

### ISSUE THREAD

**Issue by alex-berliner** [h04x/win-screenshot#2]
Hi,

Thanks for making win-screenshot! It's basically the only screenshot lib I've found that allows capturing specific windows.

I am capturing a subregion of a window in a loop and found that passing my desired width and height dimensions to CreateCompatibleBitmap is much faster than capturing the whole window and then paring down the image buffer afterwards. **Can a new capture_window function be added with x,y,w,h parameters?**

Thank you

**Comment by h04x** [comment]
I tried to adding ```capture_window_ex(hwnd, Area, Some([x, y, w, h]))``` in new [branch](https://github.com/h04x/win-screenshot/tree/capture_window_ex).
 
Unfortunally [bench](https://github.com/h04x/win-screenshot/blob/62c549b4c6c178518fdf263301751c0f21bee543/benches/capture_window_rect.rs) shows same performance 
```
crop/using_image_crate  time:   [16.623 ms 16.731 ms 16.854 ms]
                        change: [-0.6407% +0.3123% +1.3448%] (p = 0.55 > 0.05)

crop/using_capture_window_ex
                        time:   [16.587 ms 16.732 ms 16.916 ms]
                        change: [-6.3319% -1.9305% +1.0652%] (p = 0.43 > 0.05)
```
Using GDI, I did not find a way to move X and Y other than by copying ```PrintWindow()``` output to a new ```HBITMAP```.
Using ```BitBlt()``` instead ```PrintWindow()``` often gives a black screen.

**Comment by alex-berliner** [comment]
Your benchmarks helped me realize the importance of optimizations flags for this library. Max optimizations cut the screenshot time from ~120ms to ~35ms.
To turn on max optimization for your lib only across everything my project generates I did this:
```
[profile.dev.package.win-screenshot]
opt-level = 3
```

Thanks for the help!

**Comment by h04x** [comment]
I found that in some cases, "build-in" crop is more efficient on large windows. I think it would be useful to add it

Firefox 1920x1200
```
crop/using_image_crate  time:   [35.934 ms 37.112 ms 38.339 ms]
                        change: [-1.3989% +3.3386% +8.3034%] (p = 0.18 > 0.05)
crop/using_capture_window_ex
                        time:   [18.689 ms 19.349 ms 20.055 ms]
                        change: [-31.206% -26.286% -20.927%] (p = 0.00 < 0.05)
```
