### ISSUE TITLE
Is there a recommended way to unminimize a window?

### ISSUE THREAD

**Issue by kwinz** [h04x/win-screenshot#4]
I am really impressed with this crate regarding capturing individual windows!
Capturing works with windows that are
* covered by other windows
* partially outside the monitor space
* on a different Virtual Desktop 
* or even overlapping different screens with different scaling/dpi settings

The only thing that is not quite perfect is that if the window is minimized then only a few pixels of the maximize and close button are screenshotted.

Is there a recommended way to programmatically unminimize a window before taking a screenshot?

**Comment by h04x** [comment]
Hello. Thaks for feedback

I haven't solved this problem before. In the Internet
advise to use `PostMessage(hWnd, WM_SYSCOMMAND, SC_RESTORE, 0)`
