### ISSUE TITLE
Screenshot is completely broken

### ISSUE THREAD

**Issue by gucki** [h04x/win-screenshot#5]
The screenshot taken by the example (full screen) is completly broken:

![image](https://github.com/h04x/win-screenshot/assets/175494/74532169-5ea0-400a-8cc7-ae3c6308167a)

    use image::RgbaImage;
    use win_screenshot::prelude::*;

    fn main() {
        let buf = capture_display().unwrap();
        let img = RgbaImage::from_raw(buf.width, buf.height, buf.pixels).unwrap();
        img.save("screenshot.jpg").unwrap();
    }

Is it because I cross-compile on ubuntu linux using `cargo build --target x86_64-pc-windows-gnu`?

I executed the complied example on a virtual (qemu/kvm) win10 machine.

**Comment by gucki** [comment]
It seems to be a problem with the jpeg encoder. Saving as png works just fine.

**Comment by h04x** [comment]
Hello. Ty for issue investigation.
Related https://github.com/image-rs/image/issues/2188
